
GET http://localhost:8080/usuarios HTTP/1.1
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjliZTJiNmU2LTFhZDctNDgwMS1hNDZjLWY5NzcwODg1NzYxZiIsIm5vbWUiOiJHYWJyaWVsIiwidXNlcm5hbWUiOiJnYWJyaWVsY2FtcG9vcyIsImlhdCI6MTcxNTc0MTgyNSwiZXhwIjoxNzE1NzQ1NDI1fQ.07IryPmvfVQWEJipfLxq0gD8dlHF-aB91Vo-CD94ejI